name: Build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    name: Build (Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      # Atualizar submódulos
      - name: Update submodules
        run: git submodule update --init --recursive
        shell: bash

      # Clonar e preparar o vcpkg
      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
          C:\vcpkg\bootstrap-vcpkg.bat

      # Instalar dependências via vcpkg
      - name: Install dependencies
        run: |
          C:\vcpkg\vcpkg install sdl2 ogg vorbis theora

      # Build usando o make do mingw ou equivalente
      - name: Install make
        run: choco install make -y

      - name: Build
        run: make
        shell: cmd
