name: Build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libasound2-dev \
            libgl1-mesa-dev \
            libglu1-mesa-dev \
            libpng-dev \
            libfreetype6-dev \
            zlib1g-dev \
            libtheora-dev \
            libsdl2-dev

      - name: Build
        run: make -j$(nproc)
